// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: gateway_profession.proto

package admin_api_gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayProfession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
}

func (x *GatewayProfession) Reset() {
	*x = GatewayProfession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_profession_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayProfession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayProfession) ProtoMessage() {}

func (x *GatewayProfession) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_profession_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayProfession.ProtoReflect.Descriptor instead.
func (*GatewayProfession) Descriptor() ([]byte, []int) {
	return file_gateway_profession_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayProfession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GatewayProfession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GatewayCreateProfessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
}

func (x *GatewayCreateProfessionReq) Reset() {
	*x = GatewayCreateProfessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_profession_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayCreateProfessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCreateProfessionReq) ProtoMessage() {}

func (x *GatewayCreateProfessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_profession_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCreateProfessionReq.ProtoReflect.Descriptor instead.
func (*GatewayCreateProfessionReq) Descriptor() ([]byte, []int) {
	return file_gateway_profession_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayCreateProfessionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GatewayProfessionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfessionId string `protobuf:"bytes,1,opt,name=profession_id,json=professionId,proto3" json:"profession_id"`
}

func (x *GatewayProfessionId) Reset() {
	*x = GatewayProfessionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_profession_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayProfessionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayProfessionId) ProtoMessage() {}

func (x *GatewayProfessionId) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_profession_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayProfessionId.ProtoReflect.Descriptor instead.
func (*GatewayProfessionId) Descriptor() ([]byte, []int) {
	return file_gateway_profession_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayProfessionId) GetProfessionId() string {
	if x != nil {
		return x.ProfessionId
	}
	return ""
}

type GatewayGetAllProfessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit"`
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
}

func (x *GatewayGetAllProfessionRequest) Reset() {
	*x = GatewayGetAllProfessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_profession_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayGetAllProfessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayGetAllProfessionRequest) ProtoMessage() {}

func (x *GatewayGetAllProfessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_profession_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayGetAllProfessionRequest.ProtoReflect.Descriptor instead.
func (*GatewayGetAllProfessionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_profession_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayGetAllProfessionRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GatewayGetAllProfessionRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GatewayGetAllProfessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GatewayGetAllProfessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Professions []*GatewayProfession `protobuf:"bytes,1,rep,name=professions,proto3" json:"professions"`
	Count       uint32               `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
}

func (x *GatewayGetAllProfessionResponse) Reset() {
	*x = GatewayGetAllProfessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_profession_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayGetAllProfessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayGetAllProfessionResponse) ProtoMessage() {}

func (x *GatewayGetAllProfessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_profession_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayGetAllProfessionResponse.ProtoReflect.Descriptor instead.
func (*GatewayGetAllProfessionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_profession_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayGetAllProfessionResponse) GetProfessions() []*GatewayProfession {
	if x != nil {
		return x.Professions
	}
	return nil
}

func (x *GatewayGetAllProfessionResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_gateway_profession_proto protoreflect.FileDescriptor

var file_gateway_profession_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50,
	0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a,
	0x1a, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x3a, 0x0a, 0x13, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x1e, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x66,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x76, 0x0a, 0x1f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_profession_proto_rawDescOnce sync.Once
	file_gateway_profession_proto_rawDescData = file_gateway_profession_proto_rawDesc
)

func file_gateway_profession_proto_rawDescGZIP() []byte {
	file_gateway_profession_proto_rawDescOnce.Do(func() {
		file_gateway_profession_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_profession_proto_rawDescData)
	})
	return file_gateway_profession_proto_rawDescData
}

var file_gateway_profession_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gateway_profession_proto_goTypes = []interface{}{
	(*GatewayProfession)(nil),               // 0: genproto.GatewayProfession
	(*GatewayCreateProfessionReq)(nil),      // 1: genproto.GatewayCreateProfessionReq
	(*GatewayProfessionId)(nil),             // 2: genproto.GatewayProfessionId
	(*GatewayGetAllProfessionRequest)(nil),  // 3: genproto.GatewayGetAllProfessionRequest
	(*GatewayGetAllProfessionResponse)(nil), // 4: genproto.GatewayGetAllProfessionResponse
}
var file_gateway_profession_proto_depIdxs = []int32{
	0, // 0: genproto.GatewayGetAllProfessionResponse.professions:type_name -> genproto.GatewayProfession
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_profession_proto_init() }
func file_gateway_profession_proto_init() {
	if File_gateway_profession_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_profession_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayProfession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_profession_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayCreateProfessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_profession_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayProfessionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_profession_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayGetAllProfessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_profession_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayGetAllProfessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_profession_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_profession_proto_goTypes,
		DependencyIndexes: file_gateway_profession_proto_depIdxs,
		MessageInfos:      file_gateway_profession_proto_msgTypes,
	}.Build()
	File_gateway_profession_proto = out.File
	file_gateway_profession_proto_rawDesc = nil
	file_gateway_profession_proto_goTypes = nil
	file_gateway_profession_proto_depIdxs = nil
}
